[package]
name = "taskers"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[[bin]]
name = "taskers"
path = "src/main.rs"

[dependencies]
adw.workspace = true
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
dioxus.workspace = true
dioxus-liveview.workspace = true
gtk.workspace = true
taskers-app-core.workspace = true
taskers-control.workspace = true
taskers-core.workspace = true
taskers-domain.workspace = true
taskers-ghostty.workspace = true
taskers-host.workspace = true
taskers-paths.workspace = true
taskers-runtime.workspace = true
taskers-shell.workspace = true
tokio.workspace = true
webkit6.workspace = true
