[package]
name = "taskers"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[[bin]]
name = "taskers"
path = "src/main.rs"

[dependencies]
clap.workspace = true
dioxus.workspace = true
dioxus-desktop.workspace = true
gtk.workspace = true
taskers-core.workspace = true
taskers-host.workspace = true
taskers-paths.workspace = true
taskers-runtime.workspace = true
taskers-shell.workspace = true
tokio.workspace = true
