[package]
name = "taskers-cli"
description = "CLI for querying and controlling the local taskers app."
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme = "../../README.md"
repository.workspace = true
version.workspace = true

[[bin]]
name = "taskersctl"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde_json.workspace = true
time.workspace = true
tokio.workspace = true
taskers-control = { version = "0.4.0", path = "../taskers-control" }
taskers-domain = { version = "0.4.0", path = "../taskers-domain" }
taskers-paths.workspace = true
taskers-runtime = { version = "0.4.0", path = "../taskers-runtime" }
