[package]
name = "taskers-control"
description = "Control protocol and local socket transport for taskers."
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme = "../../README.md"
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
taskers-paths.workspace = true
taskers-domain = { version = "0.5.0", path = "../taskers-domain" }

[dev-dependencies]
tempfile.workspace = true
