[package]
name = "taskers-core"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
parking_lot.workspace = true
taskers-app-core.workspace = true
taskers-control.workspace = true
taskers-domain.workspace = true
taskers-ghostty.workspace = true
taskers-runtime.workspace = true
time.workspace = true
tokio.workspace = true
